# See https://pre-commit.com for more information
exclude: proposal/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
        -   id: double-quote-string-fixer
        -   id: check-added-large-files
            args: ['--maxkb=600']
        -   id: check-ast
        -   id: check-json
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: no-commit-to-branch
        -   id: fix-encoding-pragma
        -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7' # 'v1.4.4'  # Use the sha / tag you want to point at
    hooks:
        -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910' # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies:
            # Also added to the environment.yml
            - git+https://github.com/numpy/numpy-stubs.git
            - 'pydantic'
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
        -   id: forbid-tabs
        -   id: remove-tabs
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: ^proposal/
        additional_dependencies: [pep8-naming]
